# Cross-platform testing with different Python versions
version: '3.8'

services:
  # Test matrix for different Python versions
  test-matrix:
    profiles:
      - matrix
    build:
      context: .
      target: base
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11}
    depends_on:
      redis-matrix:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis-matrix
      - REDIS_PORT=6379
      - PYTHON_VERSION=${PYTHON_VERSION:-3.11}
    volumes:
      - .:/app:delegated
    command: |
      bash -c "
        echo 'Testing on Python ${PYTHON_VERSION:-3.11}' &&
        uv run pytest -v --tb=short
      "

  # Concurrent testing with multiple Python versions
  test-py38:
    build:
      context: .
      target: test-py38
    depends_on:
      redis-matrix:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis-matrix
      - REDIS_PORT=6379
    volumes:
      - .:/app:delegated

  test-py39:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.9
    depends_on:
      redis-matrix:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis-matrix
      - REDIS_PORT=6379
    volumes:
      - .:/app:delegated
    command: uv run pytest -v --tb=short

  test-py310:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.10
    depends_on:
      redis-matrix:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis-matrix
      - REDIS_PORT=6379
    volumes:
      - .:/app:delegated
    command: uv run pytest -v --tb=short

  test-py311:
    build:
      context: .
      target: test
    depends_on:
      redis-matrix:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis-matrix
      - REDIS_PORT=6379
    volumes:
      - .:/app:delegated

  test-py312:
    build:
      context: .
      target: test-py312
    depends_on:
      redis-matrix:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis-matrix
      - REDIS_PORT=6379
    volumes:
      - .:/app:delegated

  redis-matrix:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  redis_matrix_data:
