name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:  # Allow manual triggering
  workflow_call: # Allow referencing

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Linux testing with Redis support
  test-linux:
    name: Test Python ${{ matrix.python-version }} on Linux (with Redis)
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with Redis
        run: uv sync --extra test --extra redis

      - name: Install Redis CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools

      - name: Wait for Redis
        run: |
          echo "Waiting for Redis to be ready..."
          timeout 30 bash -c 'until redis-cli -h localhost -p 6379 ping 2>/dev/null; do sleep 1; done'
          echo "Redis is ready!"

      - name: Run full test suite with coverage
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: |
          uv run pytest \
            --cov=src/traffik \
            --cov-branch \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-fail-under=80 \
            --tb=short \
            -v

      - name: Upload coverage to Codecov
        if: matrix.python-version == '3.11'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  # Windows and macOS testing without Redis (containers not supported)
  test-cross-platform:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }} (no Redis)
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ["3.8", "3.11", "3.12"]  # Test fewer versions for speed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (no Redis)
        run: uv sync --extra test

      - name: Run tests without Redis
        run: |
          uv run pytest tests/ -k "not redis and not Redis" -v --tb=short

  # Test installation from built package
  test-install:
    name: Test Package Installation
    runs-on: ubuntu-latest
    needs: [test-linux]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build package
        run: uv build

      - name: Install built package
        run: |
          cd dist
          uv pip install --system traffik-*.whl

      - name: Test installation
        run: |
          python -c "
          import traffik
          from traffik.backends.inmemory import InMemoryBackend
          from traffik.throttles import HTTPThrottle
          print('✅ Package installed and imports work')
          "

  # Test with minimal dependencies
  test-minimal:
    name: Test Minimal Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install minimal dependencies
        run: |
          uv sync --extra test

      - name: Run tests without Redis
        run: |
          uv run pytest tests/ -k "not redis and not Redis and not concurrent" -v --tb=short
